FROM python:3.12-slim

WORKDIR /repo
COPY db/schema.sql db/schema.sql
COPY api/requirements.txt api/requirements.txt
COPY api/dev-requirements.txt api/dev-requirements.txt
RUN pip install --no-cache-dir -r api/dev-requirements.txt
COPY api/app api/app
COPY api/tests api/tests
COPY api/pytest.ini api/pytest.ini

WORKDIR /repo/api
CMD ["pytest"]
